### ISSUE TITLE
integrate the possibility to configure the log pattern and location

### ISSUE THREAD

**Issue by minderjan** [muuvy/muuvy-backend#7]
### Customer value
as developer I want to configure my log format and location (file or stdout)

### Acceptance criteria
- the project has a sample config with a log pattern
- the project has a default config to log in a log file

### Comment
- [Logging Docs Thorntail] https://docs.thorntail.io/2.4.0.Final/#_logging

**Comment by xXx-DoMoDo-xXx** [comment]
### Comment


- [x] the project has a sample config with a log pattern
- [x] the project has a default config to log in a log file

- POM.xml thorntail logging dependencies extended
- project-local.yml extended, here you can see the logging information. Actually will be log ERROR and FATAL only in the File and console includes all messages.

You must put this:
`private static final Logger LOG = Logger.getLogger(HelloWorldEndpoint.class);`
in the class.

You can log in by entering:
`LOG.info("put your information");`
